# Generated by Django 5.0.2 on 2024-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('password1', models.CharField(max_length=200)),
            ],
        ),
    ]
