# Generated by Django 5.0.2 on 2024-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=200)),
                ('drname', models.CharField(max_length=200, null=True)),
                ('datepicker', models.CharField(max_length=200, null=True)),
                ('symptoms', models.CharField(max_length=200)),
            ],
        ),
    ]
